### ISSUE TITLE
Docker images running in OpenShift

### ISSUE THREAD

**Issue by vsimko** [biggis-project/biggis-infrastructure#3]
Would it make sense to run some infrastructure in OpenShift?

See also:
https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/containers_and_images.html

**Comment by wipatrick** [comment]
You mean for test purposes? You can host up to 3 applications for free according to their pricing model.

Afaik, OpenShift leverages Docker container scheduling by using [Kubernetes](http://kubernetes.io/). Up until now, I haven't used Kubernetes but I as of my researches it's a very great tool in combination with recent minimal OS (CoreOS etc) for managing (Docker) containers.

Definitely, there is some overlap between Kubernetes and e.g. Mesos which I'm considering right now to be a better fit for our integrated prototype (M3) since it is not only limited to containers.

However, I can envision something of this sort for future:

Kubernetes can run on top of Mesos so you can abstract away HA from Kubernetes and hand it over to Mesos, in particular to a service monitoring framework like Marathon or Apache Aurora, in order to ensure Kubernetes components that are managing Docker containers are up and running with zero downtime. On the other hand, non container applications can then still be managed via Marathon/Aurora in the Mesos cluster in order to share resources. This can be on-premise, in the cloud or some hybrid solution.

**Comment by wipatrick** [comment]
I'd consider to close this issue for now.
